// Classic Spyfall locations with roles (72 locations, 8 roles each)
const spyfallClassic = {
  'Uçak': ['Pilot', 'Yardımcı Pilot', 'Hostes', 'Yolcu', 'Güvenlik Görevlisi (Air Marshal)', 'Teknisyen', 'Çocuk Yolcu', 'Bavul Taşıyıcısı'],
  'Banka': ['Banka Müdürü', 'Veznedar', 'Güvenlik Görevlisi', 'Müşteri', 'Hırsız', 'Temizlikçi', 'Sigortacı', 'Polis Memuru'],
  'Plaj': ['Can Kurtaran', 'Güneşlenen Tatilci', 'Dondurmacı', 'Çocuk', 'Sörfçü', 'Balıkçı', 'Şezlong Satıcısı', 'Fotoğrafçı'],
  'Tiyatro Salonu': ['Oyuncu', 'Yönetmen', 'Işıkçı', 'Sahne İşçisi', 'Seyirci', 'Biletçi', 'Orkestra Üyesi', 'Kostüm Tasarımcısı'],
  'Kumarhane': ['Kurpiyer', 'Kumarbaz', 'Zengin İş Adamı', 'Güvenlik Görevlisi', 'Garson', 'Hileci', 'Turist', 'Patron'],
  'Cami': ['İmam', 'Müezzin', 'Cemaat Üyesi', 'Hoca Yardımcısı', 'Öğrenci', 'Hizmetli', 'Ziyaretçi', 'Çocuk'],
  'Kilise': ['Rahip', 'Koro Üyesi', 'Gelin', 'Damat', 'Cemaat Üyesi', 'Organ Çalıcı', 'Papaz Yardımcısı', 'Turist'],
  'Sirk Çadırı': ['Palyaço', 'Aslan Terbiyecisi', 'Cambaz', 'Seyirci', 'Biletçi', 'Güvenlikçi', 'Çocuk Seyirci', 'Sihirbaz'],
  'Şirket Partisi': ['CEO', 'Çalışan', 'Garson', 'DJ', 'Yeni İşe Alınan', 'Güvenlik', 'Patronun Yakını', 'Fotoğrafçı'],
  'Haçlı Ordusu': ['Komutan', 'Asker', 'Okçu', 'Rahip', 'Şövalye', 'Katip', 'Kılıç Ustası', 'Esir'],
  'Güzellik & Spa Merkezi': ['Masöz', 'Müşteri', 'Spa Müdürü', 'Resepsiyonist', 'Temizlikçi', 'Estetisyen', 'Bekleyen Arkadaş', 'Masöz'],
  'Büyükelçilik': ['Büyükelçi', 'Konsolos', 'Sekreter', 'Koruma', 'Ziyaretçi', 'Muhabir', 'Temizlikçi', 'Tercüman'],
  'Meclis': ['Milletvekili', 'Başkan', 'Sekreter', 'Güvenlikçi', 'Basın Görevlisi', 'Stajyer', 'Vatandaş', 'Lobici'],
  'Hastane': ['Doktor', 'Hemşire', 'Hasta', 'Hasta Yakını', 'Cerrah', 'Temizlik Görevlisi', 'Resepsiyonist', 'Ambulans Şoförü'],
  'Otel': ['Resepsiyonist', 'Kat Görevlisi', 'Müşteri', 'Oda Servisi Görevlisi', 'Otel Müdürü', 'Bavul Taşıyıcı', 'Turist', 'Güvenlikçi'],
  'Askeri Üs': ['General', 'Asker', 'Pilot', 'Doktor', 'Mühendis', 'Teknisyen', 'Komutan', 'Şef Aşçı'],
  'Film Stüdyosu': ['Yönetmen', 'Oyuncu', 'Kameraman', 'Işıkçı', 'Makyöz', 'Figüran', 'Yapımcı', 'Senarist'],
  'Yolcu Gemisi': ['Kaptan', 'Tayfa', 'Yolcu', 'Garson', 'Eğlence Görevlisi', 'Aşçı', 'Temizlikçi', 'Turist'],
  'Yolcu Treni': ['Makinist', 'Biletçi', 'Yolcu', 'Kompartıman Görevlisi', 'Aşçı', 'Güvenlik', 'Çocuk Yolcu', 'Bavul Taşıyıcı'],
  'Korsan Gemisi': ['Kaptan', 'Tayfa', 'Esir', 'Korsan', 'Aşçı', 'Hazine Haritacısı', 'Topçu', 'Güverte Temizleyicisi'],
  'Kutup İstasyonu': ['Bilim Adamı', 'Pilot', 'Kaptan', 'Aşçı', 'Mekanikçi', 'Fotoğrafçı', 'Doktor', 'Araştırmacı'],
  'Polis Karakolu': ['Polis Memuru', 'Komiser', 'Şüpheli', 'Avukat', 'Katip', 'Temizlikçi', 'Vatandaş', 'Mahkum'],
  'Restoran': ['Aşçı', 'Garson', 'Müşteri', 'Müdür', 'Temizlikçi', 'Kurye', 'Sommelier (Şarap Uzmanı)', 'Çocuk'],
  'Okul': ['Öğretmen', 'Öğrenci', 'Müdür', 'Müdür Yardımcısı', 'Hizmetli', 'Güvenlikçi', 'Veli', 'Kantinci'],
  'Benzin İstasyonu': ['Pompa Görevlisi', 'Müşteri', 'Kasiyer', 'Tamirci', 'Hırsız', 'Polis', 'Yoldan Geçen', 'Çocuk'],
  'Uzay İstasyonu': ['Astronot', 'Komutan', 'Bilim Adamı', 'Doktor', 'Teknisyen', 'İstasyon Görevlisi', 'Asistan', 'Pilot'],
  'Denizaltı': ['Kaptan', 'Subay', 'Asker', 'Mühendis', 'Doktor', 'Yolcu', 'İletişim Subayı', 'Aşçı'],
  'Süpermarket': ['Kasiyer', 'Müşteri', 'Müdür', 'Güvenlik', 'Temizlikçi', 'Reyon Görevlisi', 'Çocuk', 'Kasap'],
  'Üniversite': ['Profesör', 'Öğrenci', 'Dekan', 'Araştırmacı', 'Kütüphaneci', 'Güvenlikçi', 'Kantinci', 'Temizlikçi'],
  'Lunapark': ['Biletçi', 'Çarpışan Araba Görevlisi', 'Pamuk Şeker Satıcısı', 'Müşteri', 'Müşteri', 'Güvenlikçi', 'Palyaço', 'Müşteri'],
  'Sanat Müzesi': ['Ziyaretçi', 'Küratör', 'Güvenlikçi', 'Sanatçı', 'Rehber', 'Öğrenci', 'Temizlikçi', 'Restoratör'],
  'Şeker Fabrikası': ['İşçi', 'Fabrika Müdürü', 'Paketleyici', 'Mühendis', 'Güvenlikçi', 'Tat Testçisi', 'Tedarikçi', 'Temizlikçi'],
  'Mezarlık': ['Mezarcı', 'Cenaze Katılımcısı', 'Hoca', 'Çiçekçi', 'Güvenlikçi', 'Turist', 'Hayalet', 'Bekçi'],
  'Kömür Madeni': ['Madenci', 'Mühendis', 'Güvenlikçi', 'Yöneticisi', 'Doktor', 'Nakliyeci', 'Şoför', 'Çırak'],
  'İnşaat Alanı': ['İşçi', 'Mühendis', 'Usta', 'Mimar', 'Güvenlikçi', 'Vinç Operatörü', 'Malzeme Taşıyıcı', 'Çırak'],
  'Oyun Fuarı': ['Oyuncu', 'Yayıncı (Streamer)', 'Geliştirici', 'Cosplayer', 'Satıcı', 'Basın', 'Güvenlik', 'Sponsor'],
  'Liman / Rıhtım': ['Kaptan', 'Balıkçı', 'Liman Görevlisi', 'Gümrük Memuru', 'Turist', 'Yük İşçisi', 'Güvenlikçi', 'Kaçakçı'],
  'Stadyum': ['Futbolcu', 'Hakem', 'Taraftar', 'Satıcı', 'Antrenör', 'Güvenlik', 'Spiker', 'Çocuk Taraftar'],
  'Hapishane': ['Mahkum', 'Gardiyan', 'Müdür', 'Avukat', 'Aşçı', 'Kaçakçı', 'Yeni Gelen Mahkum', 'Doktor'],
  'Caz Kulübü': ['Müzisyen', 'Piyanist', 'Garson', 'Müşteri', 'Sahne Görevlisi', 'Kulüp Sahibi', 'Dansçı', 'Güvenlikçi'],
  'Kütüphane': ['Kütüphaneci', 'Öğrenci', 'Araştırmacı', 'Sessiz Çalışan', 'Güvenlikçi', 'Çocuk', 'Temizlikçi', 'Profesör'],
  'Gece Kulübü': ['DJ', 'Dansçı', 'Müşteri', 'Garson', 'Güvenlik', 'Patron', 'Barmen', 'Fotoğrafçı'],
  'Yarış Pisti': ['Yarışçı', 'Mekanik', 'Seyirci', 'Hakem', 'Pit Stop Görevlisi', 'Sponsor', 'Gazeteci', 'Güvenlik'],
  'Huzurevi': ['Emekli', 'Hemşire', 'Doktor', 'Ziyaretçi', 'Temizlikçi', 'Resepsiyonist', 'Güvenlikçi', 'Psikolog'],
  'Konser': ['Solist', 'Gitarist', 'Davulcu', 'Seyirci', 'Biletçi', 'Güvenlikçi', 'Işıkçı', 'Roadie'],
  'Otobüs': ['Şoför', 'Yolcu', 'Çocuk', 'Turist', 'Biletçi', 'Polis', 'Yaşlı Kadın', 'Öğrenci'],
  'Metro': ['Masinis', 'Yolcu', 'Güvenlik', 'Kaçak Yolcu', 'Temizlikçi', 'Memur', 'Çocuk', 'Turist'],
  'Bağ Evi (Şarap Bağı)': ['Çiftçi', 'Şarap Yapımcısı', 'İşçi', 'Tadımcı', 'Turist', 'Aşçı', 'Güvenlikçi', 'Araştırmacı'],
  'Düğün': ['Gelin', 'Damat', 'Nikah Memuru', 'Şahit', 'Gelin Arkadaşı', 'Damat Arkadaşı', 'Fotoğrafçı', 'Müzisyen'],
  'Hayvanat Bahçesi': ['Zookeeper (Bakıcı)', 'Veteriner', 'Ziyaretçi', 'Çocuk', 'Satıcı', 'Güvenlik', 'Rehber', 'Araştırmacı'],
  'Kafe': ['Barista', 'Kasiyer', 'Müşteri', 'Öğrenci', 'İş Adamı', 'Yazar', 'Çocuk', 'Garson'],
  'Kıraathane': ['Kahveci', 'Gazete Okuyan', 'Tavla Oyuncusu', 'Çaycı', 'Emekli', 'Sohbet Eden', 'Öğrenci', 'Esnaf'],
  'Botanik Bahçesi': ['Bahçıvan', 'Ziyaretçi', 'Öğrenci', 'Botanikçi', 'Fotoğrafçı', 'Çocuk', 'Turist', 'Güvenlikçi'],
  'Havuz': ['Can Kurtaran', 'Yüzücü', 'Çocuk', 'Antrenör', 'Temizlikçi', 'Güvenlik', 'Aile', 'Kiosk Satıcısı'],
  'Gym': ['Antrenör', 'Sporcu', 'Yeni Başlayan', 'Kaslı Adam', 'Ziyaretçi', 'Resepsiyonist', 'Temizlikçi', 'Diyetisyen'],
  'Türbe': ['Türbedar', 'Ziyaretçi', 'Çocuk', 'Öğrenci', 'Turist', 'Güvenlikçi', 'Rehber', 'Yaşlı Kadın'],
  'Kırtasiye': ['Satıcı', 'Öğrenci', 'Öğretmen', 'Kasiyer', 'Raf Görevlisi', 'Çocuk', 'Müşteri', 'Dağıtıcı'],
  'Pastane / Fırın': ['Fırıncı', 'Kasiyer', 'Müşteri', 'Çırak', 'Çocuk', 'Garson', 'Aşçı', 'Teslimatçı'],
  'Bar': ['Barmen', 'Müşteri', 'DJ', 'Garson', 'Güvenlikçi', 'Sarhoş', 'Patron', 'Temizlikçi'],
  'Otopark': ['Görevli', 'Müşteri', 'Hırsız', 'Polis', 'Çocuk', 'Güvenlikçi', 'Bekçi', 'Araba Yıkamacı'],
  'Alışveriş Merkezi': ['Mağaza Satıcısı', 'Kasiyer', 'Müşteri', 'Güvenlikçi', 'Çocuk', 'Temizlikçi', 'Fast Food Çalışanı', 'Yönetici'],
  'İnternet Kafe': ['Oyuncu', 'Çalışan', 'Öğrenci', 'Çocuk', 'Öğretmen', 'Sahip', 'Teknik Servisçi', 'Müşteri'],
  'Kuaför': ['Kuaför', 'Müşteri', 'Çırak', 'Manikürcü', 'Çocuk', 'Kadın', 'Erkek', 'Temizlikçi'],
  'Mahkeme Salonu': ['Hakim', 'Avukat', 'Sanık', 'Davacı', 'Katip', 'Polis', 'Tanık', 'Seyirci'],
  'Sinema Salonu': ['Biletçi', 'Seyirci', 'Görevli', 'Temizlikçi', 'Projeksiyoncu', 'Seyirci', 'Mısır Satıcısı', 'Güvenlik'],
  'Opera': ['Opera Sanatçısı', 'Seyirci', 'Orkestra Şefi', 'Orkestra Üyesi', 'Sahne Görevlisi', 'Işıkçı', 'Biletçi', 'Temizlikçi'],
  'Aqua Park': ['Kaydırak Görevlisi', 'Çocuk', 'Genç', 'Can Kurtaran', 'Satıcı', 'Güvenlik', 'Yüzücü', 'Fotoğrafçı'],
  'Sauna': ['Müşteri', 'Masör', 'Görevli', 'Temizlikçi', 'Müşteri', 'Çocuk', 'Sporcu', 'Sauna Müdürü'],
  'Şu anki konum': ['Sen', 'Sen', 'Sen', 'Sen', 'Sen', 'Sen', 'Sen', 'Sen']
};

module.exports = spyfallClassic;
